// Code generated by cmd/genapi. DO NOT EDIT.

import webapi from "./gocliRequest"
import * as components from "./gosaasComponents"
export * from "./gosaasComponents"

/**
 * @description "Health check"
 */
export function healthCheck() {
	return webapi.get<components.HealthResponse>(`/health`)
}

/**
 * @description "Get auth config"
 */
export function getAuthConfig() {
	return webapi.get<components.AuthConfigResponse>(`/api/v1/auth/config`)
}

/**
 * @description "Forgot password"
 * @param req
 */
export function forgotPassword(req: components.ForgotPasswordRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/forgot-password`, req)
}

/**
 * @description "Login"
 * @param req
 */
export function login(req: components.LoginRequest) {
	return webapi.post<components.LoginResponse>(`/api/v1/auth/login`, req)
}

/**
 * @description "Refresh token"
 * @param req
 */
export function refreshToken(req: components.RefreshTokenRequest) {
	return webapi.post<components.RefreshTokenResponse>(`/api/v1/auth/refresh`, req)
}

/**
 * @description "Register"
 * @param req
 */
export function register(req: components.RegisterRequest) {
	return webapi.post<components.LoginResponse>(`/api/v1/auth/register`, req)
}

/**
 * @description "Resend verification"
 * @param req
 */
export function resendVerification(req: components.ResendVerificationRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/resend-verification`, req)
}

/**
 * @description "Reset password"
 * @param req
 */
export function resetPassword(req: components.ResetPasswordRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/reset-password`, req)
}

/**
 * @description "Verify email"
 * @param req
 */
export function verifyEmail(req: components.EmailVerificationRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/verify-email`, req)
}

/**
 * @description "O auth callback"
 * @param req
 */
export function oAuthCallback(req: components.OAuthLoginRequest, provider: string) {
	return webapi.post<components.OAuthLoginResponse>(`/api/v1/oauth/${provider}/callback`, req)
}

/**
 * @description "Get o auth url"
 * @param params
 */
export function getOAuthUrl(params: components.GetOAuthUrlRequestParams, provider: string) {
	return webapi.get<components.GetOAuthUrlResponse>(`/api/v1/oauth/${provider}/url`, params)
}

/**
 * @description "Get invite by token"
 */
export function getInviteByToken(token: string) {
	return webapi.get<components.GetInviteByTokenResponse>(`/api/v1/organizations/invites/${token}`)
}

/**
 * @description "List plans"
 */
export function listPlans() {
	return webapi.get<components.ListPlansResponse>(`/api/v1/subscription/plans`)
}

/**
 * @description "List notifications"
 * @param params
 */
export function listNotifications(params: components.ListNotificationsRequestParams) {
	return webapi.get<components.ListNotificationsResponse>(`/api/v1/notifications`, params)
}

/**
 * @description "Delete notification"
 */
export function deleteNotification(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/notifications/${id}`)
}

/**
 * @description "Mark notification read"
 */
export function markNotificationRead(id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/notifications/${id}/read`)
}

/**
 * @description "Mark all notifications read"
 */
export function markAllNotificationsRead() {
	return webapi.put<components.MessageResponse>(`/api/v1/notifications/read-all`)
}

/**
 * @description "Get unread count"
 */
export function getUnreadCount() {
	return webapi.get<components.GetUnreadCountResponse>(`/api/v1/notifications/unread-count`)
}

/**
 * @description "Disconnect o auth"
 */
export function disconnectOAuth(provider: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/oauth/${provider}`)
}

/**
 * @description "List o auth providers"
 */
export function listOAuthProviders() {
	return webapi.get<components.ListOAuthProvidersResponse>(`/api/v1/oauth/providers`)
}

/**
 * @description "Create organization"
 * @param req
 */
export function createOrganization(req: components.CreateOrganizationRequest) {
	return webapi.post<components.CreateOrganizationResponse>(`/api/v1/organizations`, req)
}

/**
 * @description "List organizations"
 */
export function listOrganizations() {
	return webapi.get<components.ListOrganizationsResponse>(`/api/v1/organizations`)
}

/**
 * @description "Get organization"
 */
export function getOrganization(id: string) {
	return webapi.get<components.GetOrganizationResponse>(`/api/v1/organizations/${id}`)
}

/**
 * @description "Update organization"
 * @param req
 */
export function updateOrganization(req: components.UpdateOrganizationRequest, id: string) {
	return webapi.put<components.GetOrganizationResponse>(`/api/v1/organizations/${id}`, req)
}

/**
 * @description "Delete organization"
 */
export function deleteOrganization(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/organizations/${id}`)
}

/**
 * @description "Invite member"
 * @param req
 */
export function inviteMember(req: components.InviteMemberRequest, id: string) {
	return webapi.post<components.InviteMemberResponse>(`/api/v1/organizations/${id}/invites`, req)
}

/**
 * @description "List invites"
 */
export function listInvites(id: string) {
	return webapi.get<components.ListInvitesResponse>(`/api/v1/organizations/${id}/invites`)
}

/**
 * @description "Leave organization"
 */
export function leaveOrganization(id: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/organizations/${id}/leave`)
}

/**
 * @description "List members"
 */
export function listMembers(id: string) {
	return webapi.get<components.ListMembersResponse>(`/api/v1/organizations/${id}/members`)
}

/**
 * @description "Revoke invite"
 */
export function revokeInvite(orgId: string, inviteId: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/organizations/${orgId}/invites/${inviteId}`)
}

/**
 * @description "Update member role"
 * @param req
 */
export function updateMemberRole(req: components.UpdateMemberRoleRequest, orgId: string, userId: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/organizations/${orgId}/members/${userId}`, req)
}

/**
 * @description "Remove member"
 */
export function removeMember(orgId: string, userId: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/organizations/${orgId}/members/${userId}`)
}

/**
 * @description "Accept invite"
 * @param req
 */
export function acceptInvite(req: components.AcceptInviteRequest) {
	return webapi.post<components.AcceptInviteResponse>(`/api/v1/organizations/invites/accept`, req)
}

/**
 * @description "Switch organization"
 * @param req
 */
export function switchOrganization(req: components.SwitchOrganizationRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/organizations/switch`, req)
}

/**
 * @description "Get subscription"
 */
export function getSubscription() {
	return webapi.get<components.GetSubscriptionResponse>(`/api/v1/subscription`)
}

/**
 * @description "List billing history"
 * @param params
 */
export function listBillingHistory(params: components.ListBillingHistoryRequestParams) {
	return webapi.get<components.ListBillingHistoryResponse>(`/api/v1/subscription/billing-history`, params)
}

/**
 * @description "Create billing portal"
 */
export function createBillingPortal() {
	return webapi.post<components.CreateBillingPortalResponse>(`/api/v1/subscription/billing-portal`)
}

/**
 * @description "Cancel subscription"
 * @param req
 */
export function cancelSubscription(req: components.CancelSubscriptionRequest) {
	return webapi.post<components.CancelSubscriptionResponse>(`/api/v1/subscription/cancel`, req)
}

/**
 * @description "Check feature"
 * @param req
 */
export function checkFeature(req: components.CheckFeatureRequest) {
	return webapi.post<components.CheckFeatureResponse>(`/api/v1/subscription/check-feature`, req)
}

/**
 * @description "Create checkout"
 * @param req
 */
export function createCheckout(req: components.CreateCheckoutRequest) {
	return webapi.post<components.CreateCheckoutResponse>(`/api/v1/subscription/checkout`, req)
}

/**
 * @description "Get usage stats"
 */
export function getUsageStats() {
	return webapi.get<components.GetUsageStatsResponse>(`/api/v1/subscription/usage`)
}

/**
 * @description "Get current user"
 */
export function getCurrentUser() {
	return webapi.get<components.GetUserResponse>(`/api/v1/user/me`)
}

/**
 * @description "Update current user"
 * @param req
 */
export function updateCurrentUser(req: components.UpdateUserRequest) {
	return webapi.put<components.GetUserResponse>(`/api/v1/user/me`, req)
}

/**
 * @description "Delete account"
 * @param req
 */
export function deleteAccount(req: components.DeleteAccountRequest) {
	return webapi.delete<components.MessageResponse>(`/api/v1/user/me`, req)
}

/**
 * @description "Change password"
 * @param req
 */
export function changePassword(req: components.ChangePasswordRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/user/me/change-password`, req)
}

/**
 * @description "Get preferences"
 */
export function getPreferences() {
	return webapi.get<components.GetPreferencesResponse>(`/api/v1/user/me/preferences`)
}

/**
 * @description "Update preferences"
 * @param req
 */
export function updatePreferences(req: components.UpdatePreferencesRequest) {
	return webapi.put<components.GetPreferencesResponse>(`/api/v1/user/me/preferences`, req)
}

/**
 * @description "Get admin stats"
 */
export function getAdminStats() {
	return webapi.get<components.AdminStatsResponse>(`/api/v1/admin/stats`)
}

/**
 * @description "Admin list subscriptions"
 * @param params
 */
export function adminListSubscriptions(params: components.AdminListSubscriptionsRequestParams) {
	return webapi.get<components.AdminListSubscriptionsResponse>(`/api/v1/admin/subscriptions`, params)
}

/**
 * @description "Admin list users"
 * @param params
 */
export function adminListUsers(params: components.AdminListUsersRequestParams) {
	return webapi.get<components.AdminListUsersResponse>(`/api/v1/admin/users`, params)
}

