// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

export interface BillingRecord {
	id: string
	amount: number
	currency: string
	status: string
	description?: string
	invoiceDate: string
	paidAt?: string
	invoicePdfUrl?: string
	hostedInvoiceUrl?: string
}

export interface CancelSubscriptionRequest {
	cancelAtPeriodEnd?: boolean
}

export interface CancelSubscriptionResponse {
	message: string
	cancelledAt?: string
	effectiveAt?: string
}

export interface ChangePasswordRequest {
	currentPassword: string
	newPassword: string
}

export interface CheckFeatureRequest {
	feature: string
}

export interface CheckFeatureResponse {
	hasAccess: boolean
	feature: string
	planName: string
	message?: string
}

export interface CreateBillingPortalResponse {
	portalUrl: string
}

export interface CreateCheckoutRequest {
	planName: string
	billingCycle?: string
}

export interface CreateCheckoutResponse {
	checkoutUrl: string
}

export interface DeleteAccountRequest {
	password: string
}

export interface EmailVerificationRequest {
	token: string
}

export interface Empty {
}

export interface ForgotPasswordRequest {
	email: string
}

export interface GetPreferencesResponse {
	preferences: UserPreferences
}

export interface GetSubscriptionResponse {
	subscription: UserSubscription
	plan: SubscriptionPlan
}

export interface GetUsageStatsResponse {
	stats: UsageStats
}

export interface GetUserResponse {
	user: User
}

export interface HealthResponse {
	status: string
	version: string
	timestamp: string
}

export interface ListBillingHistoryRequest {
}
export interface ListBillingHistoryRequestParams {
	page?: number
	pageSize?: number
}

export interface ListBillingHistoryResponse {
	records: Array<BillingRecord>
	totalCount: number
	page: number
	pageSize: number
}

export interface ListPlansResponse {
	plans: Array<SubscriptionPlan>
}

export interface LoginRequest {
	email: string
	password: string
}

export interface LoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
	checkoutUrl?: string
}

export interface MessageResponse {
	message: string
}

export interface RefreshTokenRequest {
	refreshToken: string
}

export interface RefreshTokenResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface RegisterRequest {
	email: string
	password: string
	name: string
	plan?: string
}

export interface ResendVerificationRequest {
	email: string
}

export interface ResetPasswordRequest {
	token: string
	newPassword: string
}

export interface SubscriptionPlan {
	id: string
	name: string
	displayName: string
	description: string
	price: number
	currency: string
	interval: string
	features: Array<string>
}

export interface UpdatePreferencesRequest {
	emailNotifications?: boolean
	marketingEmails?: boolean
	timezone?: string
	language?: string
	theme?: string
}

export interface UpdateUserRequest {
	name?: string
	avatarUrl?: string
}

export interface UsageStats {
	periodStart: string
	periodEnd: string
	meters: { [key: string]: number }
}

export interface User {
	id: string
	email: string
	name: string
	avatarUrl?: string
	emailVerified: boolean
	createdAt: string
	updatedAt: string
}

export interface UserPreferences {
	emailNotifications: boolean
	marketingEmails: boolean
	timezone: string
	language: string
	theme: string
}

export interface UserSubscription {
	id: string
	planId: string
	planName: string
	status: string
	billingCycle: string
	currentPeriodStart?: string
	currentPeriodEnd?: string
	trialEnd?: string
	cancelAtPeriodEnd: boolean
}

