// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	admin "gosaas/internal/handler/admin"
	auth "gosaas/internal/handler/auth"
	subscription "gosaas/internal/handler/subscription"
	user "gosaas/internal/handler/user"
	"gosaas/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Health check endpoint
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// Get admin dashboard stats
					Method:  http.MethodGet,
					Path:    "/admin/stats",
					Handler: admin.GetAdminStatsHandler(serverCtx),
				},
				{
					// List all subscriptions (paginated)
					Method:  http.MethodGet,
					Path:    "/admin/subscriptions",
					Handler: admin.AdminListSubscriptionsHandler(serverCtx),
				},
				{
					// List all users (paginated)
					Method:  http.MethodGet,
					Path:    "/admin/users",
					Handler: admin.AdminListUsersHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Request password reset
				Method:  http.MethodPost,
				Path:    "/auth/forgot-password",
				Handler: auth.ForgotPasswordHandler(serverCtx),
			},
			{
				// User login
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// Refresh authentication token
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				// Register new user
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				// Resend email verification
				Method:  http.MethodPost,
				Path:    "/auth/resend-verification",
				Handler: auth.ResendVerificationHandler(serverCtx),
			},
			{
				// Reset password with token
				Method:  http.MethodPost,
				Path:    "/auth/reset-password",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				// Verify email address with token
				Method:  http.MethodPost,
				Path:    "/auth/verify-email",
				Handler: auth.VerifyEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List all available subscription plans
				Method:  http.MethodGet,
				Path:    "/subscription/plans",
				Handler: subscription.ListPlansHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get current user's subscription
				Method:  http.MethodGet,
				Path:    "/subscription",
				Handler: subscription.GetSubscriptionHandler(serverCtx),
			},
			{
				// Get billing history
				Method:  http.MethodGet,
				Path:    "/subscription/billing-history",
				Handler: subscription.ListBillingHistoryHandler(serverCtx),
			},
			{
				// Create billing portal session for subscription management
				Method:  http.MethodPost,
				Path:    "/subscription/billing-portal",
				Handler: subscription.CreateBillingPortalHandler(serverCtx),
			},
			{
				// Cancel current subscription
				Method:  http.MethodPost,
				Path:    "/subscription/cancel",
				Handler: subscription.CancelSubscriptionHandler(serverCtx),
			},
			{
				// Check if user has access to a feature
				Method:  http.MethodPost,
				Path:    "/subscription/check-feature",
				Handler: subscription.CheckFeatureHandler(serverCtx),
			},
			{
				// Create checkout session to subscribe to a plan
				Method:  http.MethodPost,
				Path:    "/subscription/checkout",
				Handler: subscription.CreateCheckoutHandler(serverCtx),
			},
			{
				// Get current usage statistics
				Method:  http.MethodGet,
				Path:    "/subscription/usage",
				Handler: subscription.GetUsageStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get current user profile
				Method:  http.MethodGet,
				Path:    "/user/me",
				Handler: user.GetCurrentUserHandler(serverCtx),
			},
			{
				// Update current user profile
				Method:  http.MethodPut,
				Path:    "/user/me",
				Handler: user.UpdateCurrentUserHandler(serverCtx),
			},
			{
				// Delete current user account
				Method:  http.MethodDelete,
				Path:    "/user/me",
				Handler: user.DeleteAccountHandler(serverCtx),
			},
			{
				// Change password for authenticated user
				Method:  http.MethodPost,
				Path:    "/user/me/change-password",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				// Get user preferences
				Method:  http.MethodGet,
				Path:    "/user/me/preferences",
				Handler: user.GetPreferencesHandler(serverCtx),
			},
			{
				// Update user preferences
				Method:  http.MethodPut,
				Path:    "/user/me/preferences",
				Handler: user.UpdatePreferencesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
