// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Lead struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	Source    sql.NullString `json:"source"`
	Status    string         `json:"status"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt int64          `json:"created_at"`
}

type RefreshToken struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type Subscription struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	StripeCustomerID     sql.NullString `json:"stripe_customer_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	PlanID               string         `json:"plan_id"`
	Status               string         `json:"status"`
	CurrentPeriodStart   sql.NullInt64  `json:"current_period_start"`
	CurrentPeriodEnd     sql.NullInt64  `json:"current_period_end"`
	CancelAtPeriodEnd    int64          `json:"cancel_at_period_end"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
}

type User struct {
	ID                   string         `json:"id"`
	Email                string         `json:"email"`
	PasswordHash         string         `json:"password_hash"`
	Name                 string         `json:"name"`
	AvatarUrl            sql.NullString `json:"avatar_url"`
	EmailVerified        int64          `json:"email_verified"`
	EmailVerifyToken     sql.NullString `json:"email_verify_token"`
	EmailVerifyExpires   sql.NullInt64  `json:"email_verify_expires"`
	PasswordResetToken   sql.NullString `json:"password_reset_token"`
	PasswordResetExpires sql.NullInt64  `json:"password_reset_expires"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
}

type UserPreference struct {
	UserID             string `json:"user_id"`
	EmailNotifications int64  `json:"email_notifications"`
	MarketingEmails    int64  `json:"marketing_emails"`
	Timezone           string `json:"timezone"`
	Language           string `json:"language"`
	Theme              string `json:"theme"`
	UpdatedAt          int64  `json:"updated_at"`
}
