// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) error
	CheckEmailExists(ctx context.Context, email string) (int64, error)
	// Admin queries
	CountActiveSubscriptions(ctx context.Context) (int64, error)
	CountLeads(ctx context.Context, filterStatus interface{}) (int64, error)
	CountSubscriptionsFiltered(ctx context.Context, statusFilter interface{}) (int64, error)
	CountTrialSubscriptions(ctx context.Context) (int64, error)
	// Admin queries
	CountUsers(ctx context.Context) (int64, error)
	CountUsersCreatedAfter(ctx context.Context, after int64) (int64, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPreferences(ctx context.Context, userID string) (UserPreference, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteLead(ctx context.Context, id string) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteRefreshTokensByUserID(ctx context.Context, userID string) error
	DeleteSubscription(ctx context.Context, userID string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserPreferences(ctx context.Context, userID string) error
	DowngradeToFree(ctx context.Context, stripeSubscriptionID sql.NullString) error
	GetLeadByEmail(ctx context.Context, email string) (Lead, error)
	GetLeadByID(ctx context.Context, id string) (Lead, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSubscriptionByStripeCustomerID(ctx context.Context, stripeCustomerID sql.NullString) (Subscription, error)
	GetSubscriptionByStripeSubID(ctx context.Context, stripeSubscriptionID sql.NullString) (Subscription, error)
	GetSubscriptionByUserID(ctx context.Context, userID string) (Subscription, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailVerifyToken(ctx context.Context, token sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByPasswordResetToken(ctx context.Context, token sql.NullString) (User, error)
	GetUserPreferences(ctx context.Context, userID string) (UserPreference, error)
	ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error)
	ListSubscriptionsPaginated(ctx context.Context, arg ListSubscriptionsPaginatedParams) ([]ListSubscriptionsPaginatedRow, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error)
	SetEmailVerified(ctx context.Context, id string) error
	SetEmailVerifyToken(ctx context.Context, arg SetEmailVerifyTokenParams) error
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) error
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpdateSubscriptionStripeIDs(ctx context.Context, arg UpdateSubscriptionStripeIDsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
}

var _ Querier = (*Queries)(nil)
