// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END as found
FROM users WHERE LOWER(email) = LOWER(?1)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var found int64
	err := row.Scan(&found)
	return found, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, password_hash, name, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, email, password_hash, name, avatar_url, email_verified,
          email_verify_token, email_verify_expires, password_reset_token,
          password_reset_expires, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER(?1)
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailVerifyToken = `-- name: GetUserByEmailVerifyToken :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE email_verify_token = ?1
  AND email_verify_expires > strftime('%s', 'now')
LIMIT 1
`

func (q *Queries) GetUserByEmailVerifyToken(ctx context.Context, token sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailVerifyToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPasswordResetToken = `-- name: GetUserByPasswordResetToken :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE password_reset_token = ?1
  AND password_reset_expires > strftime('%s', 'now')
LIMIT 1
`

func (q *Queries) GetUserByPasswordResetToken(ctx context.Context, token sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPasswordResetToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users
SET email_verified = 1,
    email_verify_token = NULL,
    email_verify_expires = NULL,
    updated_at = strftime('%s', 'now')
WHERE id = ?1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setEmailVerified, id)
	return err
}

const setEmailVerifyToken = `-- name: SetEmailVerifyToken :exec
UPDATE users
SET email_verify_token = ?1,
    email_verify_expires = ?2,
    updated_at = strftime('%s', 'now')
WHERE id = ?3
`

type SetEmailVerifyTokenParams struct {
	Token   sql.NullString `json:"token"`
	Expires sql.NullInt64  `json:"expires"`
	ID      string         `json:"id"`
}

func (q *Queries) SetEmailVerifyToken(ctx context.Context, arg SetEmailVerifyTokenParams) error {
	_, err := q.db.ExecContext(ctx, setEmailVerifyToken, arg.Token, arg.Expires, arg.ID)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users
SET password_reset_token = ?1,
    password_reset_expires = ?2,
    updated_at = strftime('%s', 'now')
WHERE id = ?3
`

type SetPasswordResetTokenParams struct {
	Token   sql.NullString `json:"token"`
	Expires sql.NullInt64  `json:"expires"`
	ID      string         `json:"id"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, setPasswordResetToken, arg.Token, arg.Expires, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = COALESCE(?1, name),
    avatar_url = COALESCE(?2, avatar_url),
    updated_at = strftime('%s', 'now')
WHERE id = ?3
`

type UpdateUserParams struct {
	Name      sql.NullString `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.AvatarUrl, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?1,
    password_reset_token = NULL,
    password_reset_expires = NULL,
    updated_at = strftime('%s', 'now')
WHERE id = ?2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
